In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

In [2]:
pd.set_option('display.max_columns', None)
warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv('../data/players_3120_original.csv')

In [4]:
df.head()

,name,Age,Overall rating,Potential,Team & Contract,ID,Height,Weight,foot,Best overall,Best position,Growth,Value,Wage,Release clause,Total attacking,Crossing,Finishing,Heading accuracy,Short passing,Volleys,Total skill,Dribbling,Curve,FK Accuracy,Long passing,Ball control,Total movement,Acceleration,Sprint speed,Agility,Reactions,Balance,Total power,Shot power,Jumping,Stamina,Strength,Long shots,Total mentality,Aggression,Interceptions,Att. Position,Vision,Penalties,Composure,Total defending,Defensive awareness,Standing tackle,Sliding tackle,Total goalkeeping,GK Diving,GK Handling,GK Kicking,GK Positioning,GK Reflexes,Total stats,Base stats,International reputation,Pace / Diving,Shooting / Handling,Passing / Kicking,Dribbling / Reflexes,Defending / Pace,Unnamed: 64
0,15 Ronaldinho CAM ST,34,78,78,Querétaro\n2014 ~ 2016,28130,"182cm / 6'0""",76kg / 168lbs,Right,77,CAM,0,€4.1M,€45K,€0,367,84,69,50,82,82,430,86,86,87,81,90,313,50,48,73,70,72,314,74,55,41,72,72,319,60,25,66,82,86,0,78,25,28,25,54,7,14,13,6,14,1875,377,3,49,72,83,84,28,NaN
1,O. Hutchinson RM CAM,19,65,81,Ipswich Town\n2022 ~ 2025,260145,"174cm / 5'9""",65kg / 143lbs,Left,67,CAM,16,€1.8M,€3K,€4.5M,266,48,53,49,66,50,304,69,52,50,65,68,366,76,69,81,61,79,272,62,56,63,47,44,264,41,37,60,65,61,63,140,40,49,51,39,10,7,9,5,8,1651,351,1,72,54,61,70,44,NaN
2,Brahim CAM,23,82,86,Real Madrid\n2019 ~ 2027,231410,"170cm / 5'7""",68kg / 150lbs,Right,84,CAM,4,€43.5M,€145K,€92.4M,328,75,76,30,83,64,379,84,74,61,75,85,429,85,85,89,79,91,332,73,60,68,55,76,294,44,33,78,81,58,79,84,40,23,21,51,13,9,13,10,6,1897,409,1,85,74,78,85,31,NaN
3,K. Wätjen CM,17,62,80,Borussia Dortmund\n2024 ~ 2028,70728,"178cm / 5'10""",72kg / 159lbs,Right,65,CAM,18,€1M,€900,€2.3M,257,48,53,45,67,44,292,66,52,43,65,66,356,77,68,78,59,74,267,48,58,63,51,47,263,47,54,54,59,49,49,161,50,55,56,48,9,13,7,11,8,1644,353,1,72,50,59,66,52,NaN
4,A. Güler CAM RM,18,77,88,Real Madrid\n2023 ~ 2029,264309,"175cm / 5'9""",70kg / 154lbs,Left,79,CAM,11,€22M,€41K,€49.5M,340,80,68,41,81,70,403,83,84,76,79,81,380,75,69,82,69,85,308,72,50,70,43,73,316,42,55,68,80,71,77,155,52,57,46,58,13,10,11,14,10,1960,405,1,72,70,80,81,52,NaN

In [6]:
df.shape

(3120, 65)

In [8]:
df.describe()

,Age,ID,Best overall,Growth,Total attacking,Total skill,Total movement,Total power,Total mentality,Total defending,Total goalkeeping,Total stats,Base stats,International reputation,Pace / Diving,Shooting / Handling,Passing / Kicking,Dribbling / Reflexes,Defending / Pace,Unnamed: 64
count,3120.000000,3120.000000,3120.000000,3120.000000,3120.000000,3120.000000,3120.000000,3120.000000,3120.000000,3120.000000,3120.000000,3120.000000,3120.000000,3120.000000,3120.000000,3120.000000,3120.000000,3120.000000,3120.000000,0.0
mean,24.218590,236637.525321,74.368910,5.875962,291.675641,307.003846,349.397756,328.516026,293.083333,155.752564,72.398077,1797.827244,394.946474,1.450962,73.015385,61.509936,65.975321,71.527244,54.649359,NaN
std,4.876116,39161.333184,6.430639,5.714962,72.207131,75.263189,52.477820,50.544401,63.164889,64.891734,79.925173,258.036837,38.493322,0.804862,10.379235,14.111539,9.621618,8.620042,18.068982,NaN
min,16.000000,41.000000,49.000000,0.000000,51.000000,61.000000,133.000000,146.000000,72.000000,24.000000,13.000000,843.000000,253.000000,1.000000,29.000000,21.000000,31.000000,34.000000,16.000000,NaN
25%,20.000000,224285.000000,70.000000,0.000000,267.000000,280.000000,325.000000,299.000000,268.000000,97.000000,47.000000,1670.750000,369.000000,1.000000,67.000000,53.000000,60.000000,66.750000,38.000000,NaN
50%,23.000000,243017.000000,75.000000,5.000000,304.000000,321.000000,359.000000,335.000000,303.000000,174.000000,52.000000,1839.000000,398.000000,1.000000,74.000000,64.000000,67.000000,72.000000,58.000000,NaN
75%,27.000000,262621.000000,79.000000,10.000000,339.000000,357.000000,385.000000,366.000000,334.000000,212.000000,57.000000,1973.250000,422.000000,2.000000,80.000000,72.000000,73.000000,77.000000,70.000000,NaN
max,44.000000,279922.000000,93.000000,25.000000,440.000000,465.000000,462.000000,442.000000,417.000000,269.000000,433.000000,2330.000000,500.000000,5.000000,97.000000,93.000000,94.000000,94.000000,89.000000,NaN

LIMPIEZA DE DATOS

In [ ]:
#Numero total de valores nulos
df.isnull().sum().sum()

3120

In [ ]:
#Eliminacion de la columna Unnamed: 64, para deshacernos de los valores nulos
df.drop(columns='Unnamed: 64', inplace=True)

In [ ]:
#Comprobacion de que al eliminar la columna Unnamed:64 deja de haber valores nulos en el DataFrame
df.isnull().sum().sum()

0

In [12]:
#Convierte todos los nombres en minúsculas
#Reemplaza cualquier espacio o /, en un guión bajo
#Susttituye los espacios en blanco por guiones bajos
df.columns = df.columns.str.lower().str.replace(' / ','_').str.replace(' ','_')
df.columns

Index(['name', 'age', 'overall_rating', 'potential', 'team_&_contract', 'id',
       'height', 'weight', 'foot', 'best_overall', 'best_position', 'growth',
       'value', 'wage', 'release_clause', 'total_attacking', 'crossing',
       'finishing', 'heading_accuracy', 'short_passing', 'volleys',
       'total_skill', 'dribbling', 'curve', 'fk_accuracy', 'long_passing',
       'ball_control', 'total_movement', 'acceleration', 'sprint_speed',
       'agility', 'reactions', 'balance', 'total_power', 'shot_power',
       'jumping', 'stamina', 'strength', 'long_shots', 'total_mentality',
       'aggression', 'interceptions', 'att._position', 'vision', 'penalties',
       'composure', 'total_defending', 'defensive_awareness',
       'standing_tackle', 'sliding_tackle', 'total_goalkeeping', 'gk_diving',
       'gk_handling', 'gk_kicking', 'gk_positioning', 'gk_reflexes',
       'total_stats', 'base_stats', 'international_reputation', 'pace_diving',
       'shooting_handling', 'passing_kicking', 'dribbling_reflexes',
       'defending_pace'],
      dtype='object')